'use strict'

initGlobal = ->
  # message code
  MSG = {}
  MSG.INVALID_PARAMS        = 'INVALID_PARAMS'
  MSG.INVALID_LOGIN_INFO    = 'INVALID_LOGIN_INFO'
  MSG.INVALID_SESSION_ID    = 'INVALID_SESSION_ID'
  MSG.LOGIN_REQUIRED        = 'LOGIN_REQUIRED'
  MSG.USER_CONFIRM_REQUIRED = 'USER_CONFIRM_REQUIRED'
  MSG.SERVER_ERROR          = 'SERVER_ERROR'
  MSG.USERNAME_EXISTS       = 'USERNAME_EXISTS'
  MSG.LOGIN_SUCCEED         = 'LOGIN_SUCCEED'
  MSG.LOGIN_FAILED          = 'LOGIN_FAILED'
  MSG.SIGNUP_SUCCEED        = 'SIGNUP_SUCCEED'
  MSG.LOGOUT_SUCCESS        = 'LOGOUT_SUCCESS'
  MSG.USER_STATE_UPDATED    = 'USER_STATE_UPDATED'

  # orientDB type code
  OTYPE = {}
  OTYPE.BINARY        = 'BINARY'
  OTYPE.BOOLEAN       = 'BOOLEAN'
  OTYPE.BYTE          = 'BYTE'
  OTYPE.EMBEDDED      = 'EMBEDDED'
  OTYPE.EMBEDDEDLIST  = 'EMBEDDEDLIST'
  OTYPE.EMBEDDEDMAP   = 'EMBEDDEDMAP'
  OTYPE.EMBEDDEDSET   = 'EMBEDDEDSET'
  OTYPE.DECIMAL       = 'DECIMAL'
  OTYPE.FLOAT         = 'FLOAT'
  OTYPE.DATE          = 'DATE'
  OTYPE.DATETIME      = 'DATETIME'
  OTYPE.DOUBLE        = 'DOUBLE'
  OTYPE.INTEGER32     = 'INTEGER'
  OTYPE.LINK          = 'LINK'
  OTYPE.LINKLIST      = 'LINKLIST'
  OTYPE.LINKMAP       = 'LINKMAP'
  OTYPE.LINKSET       = 'LINKSET'
  OTYPE.LONG64        = 'LONG'
  OTYPE.SHORT16       = 'SHORT'
  OTYPE.STRING        = 'STRING'

  # orientDB index type
  OINDEX = {}
  OINDEX.DICTIONARY            = 'DICTIONARY'
  OINDEX.FULLTEXT              = 'FULLTEXT'
  OINDEX.UNIQUE                = 'UNIQUE'
  OINDEX.NOTUNIQUE             = 'NOTUNIQUE'
  OINDEX.DICTIONARY_HASH_INDEX = 'DICTIONARY_HASH_INDEX'
  OINDEX.FULLTEXT_HASH_INDEX   = 'FULLTEXT_HASH_INDEX'
  OINDEX.UNIQUE_HASH_INDEX     = 'UNIQUE_HASH_INDEX'
  OINDEX.NOTUNIQUE_HASH_INDEX  = 'NOTUNIQUE_HASH_INDEX'

  # attendance type
  USER_STATE = {}
  USER_STATE.ATTEND_WORK      = 'WORK'
  USER_STATE.ATTEND_OFF       = 'OFF'
  USER_STATE.ATTEND_EARLY_OFF = 'EARLY_OFF'
  USER_STATE.ATTEND_SICK_OFF  = 'SICK_OFF'
  USER_STATE.ATTEND_LEAVE     = 'LEAVE'
  USER_STATE.CONFIRM_REQUIRED = 'CONFIRM_REQUIRED'
  USER_STATE.HIRED            = 'HIRED'
  USER_STATE.READY            = 'READY'

  # manager type
  USER_CLASS = {}
  USER_CLASS.SYSTEM   = 'SYSTEM'
  USER_CLASS.CHIEF    = 'CHIEF'
  USER_CLASS.OFFICE   = 'OFFICE'
  USER_CLASS.DESIGN   = 'DESIGN'
  USER_CLASS.SAFETY   = 'SAFETY'
  USER_CLASS.QUALITY  = 'QUALITY'
  USER_CLASS.MATERIAL = 'MATERIAL'
  USER_CLASS.MANAGER  = 'MANAGER'
  USER_CLASS.MEMBER   = 'MEMBER'

  # init globals
  global.MSG        = MSG
  global.OTYPE      = OTYPE
  global.OINDEX     = OINDEX
  global.USER_STATE = USER_STATE
  global.USER_CLASS = USER_CLASS
  global.log        = console.log.bind(console)
  global.Promise    = require 'bluebird'

module.exports = initGlobal()